// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuuabpqrskpgtglfdepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dWFicHFyc2twZ3RnbGZkZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjY1MTgsImV4cCI6MjA2MDA0MjUxOH0.InzICmImJRdPfAFaDia__hk9SR49GQQPVPcE9PSbgnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);